python convert.py --input_path_json=../../../../data/simmc2_dials_dstc10_train.json \
       --disambiguate_json=../../../../data/simmc2_disambiguate_dstc10_train.json \
       --output_path_predict=../data_object_special/simmc2_dials_dstc10_train_predict.txt \
       --output_path_target=../data_object_special/simmc2_dials_dstc10_train_target.txt \
    #    --output_path_special_tokens=../data_object_special/simmc_special_tokens.json \
       --object_special_token_item2id=./item2id.json \
       --scene_json_folder=../../../../data/jsons \
       --insert_bbox_coords=1 \
       --insert_relation=0 \
       --insert_det=0 \
       --revert=0 \
       --final=0 \
       --replace_acts=0 \
       --img_size_picklefile=./img_size.pkl \
       --det_info_picklefile=./det_info.pkl

python convert.py --input_path_json=../../../../data/simmc2_dials_dstc10_dev.json \
    --disambiguate_json=../../../../data/simmc2_disambiguate_dstc10_dev.json \
    --output_path_predict=../data_object_special/simmc2_dials_dstc10_dev_predict.txt \
    --output_path_target=../data_object_special/simmc2_dials_dstc10_dev_target.txt \
    # --output_path_special_tokens=../data_object_special/simmc_special_tokens.json \
    --object_special_token_item2id=./item2id.json \
    --scene_json_folder=../../../../data/jsons \
    --insert_bbox_coords=1 \
    --insert_relation=0 \
    --insert_det=0 \
    --revert=0 \
    --final=0 \
    --replace_acts=0 \
    --img_size_picklefile=./img_size.pkl \
    --det_info_picklefile=./det_info.pkl

python convert.py --input_path_json=../../../../data/simmc2_dials_dstc10_devtest.json \
       --disambiguate_json=../../../../data/simmc2_disambiguate_dstc10_devtest.json \
       --output_path_predict=../data_object_special/simmc2_dials_dstc10_devtest_predict.txt \
       --output_path_target=../data_object_special/simmc2_dials_dstc10_devtest_target.txt \
    #    --output_path_special_tokens=../data_object_special/simmc_special_tokens.json \
       --object_special_token_item2id=./item2id.json \
       --scene_json_folder=../../../../data/jsons \
       --insert_bbox_coords=1 \
       --insert_relation=0 \
       --insert_det=0 \
       --revert=0 \
       --final=0 \
       --replace_acts=0 \
       --img_size_picklefile=./img_size.pkl \
       --det_info_picklefile=./det_info.pkl